FROM docker.io/library/python:alpine3.21

RUN apk update \
    && apk add ffmpeg \
    && apk cache clean

RUN adduser -D jobuser
USER jobuser

ENV JOB_DIR=/home/jobuser
WORKDIR $JOB_DIR
COPY --chown=jobuser:jobuser ./ops/cron/import-music/import-music.py $JOB_DIR
COPY --chown=jobuser:jobuser ./ops/cron/import-music/pyproject.toml $JOB_DIR
COPY --chown=jobuser:jobuser ./ops/cron/import-music/uv.lock $JOB_DIR

ENV PATH=$PATH:/home/jobuser/.local/bin/
RUN pip install --no-cache-dir uv==0.9.5 \
    && uv sync --frozen

CMD ["uv", "run", "./import-music.py"]
