apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-music
  namespace: apps
spec:
  concurrencyPolicy: Forbid
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-music
            image: ghcr.io/spencerkarjala/import-music:latest
            volumeMounts:
            - name: music-to-import
              mountPath: /music/todo/
            - name: music-library
              mountPath: /music/done/
          restartPolicy: Never
          volumes:
          - name: script
            hostPath:
              path: /home/skarjala/development/cinnfra/tools/import-music.py
              type: File
          - name: music-to-import
            persistentVolumeClaim:
              claimName: music-to-import
          - name: music-library
            persistentVolumeClaim:
              claimName: music
