apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - copyparty.yaml
  - metadata-remote.yaml
  - navidrome.yaml
  - openhands.yaml
  - picard.yaml
  - reference-compiler.yaml
