apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhands
  namespace: dev
spec:
  ingressClassName: traefik
  rules:
  - host: openhands.skarja.la
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: openhands
            port:
              number: 80
