apiVersion: ENC[AES256_GCM,data:SBc=,iv:e5ibSTJCNkaamXxMgDASpcZrZIZ2Pes+OYxGmTk5VYc=,tag:X1n+49KcF+F1jERAqdagUg==,type:str]
kind: ENC[AES256_GCM,data:MXaQ5JwK,iv:Un9o3UtwyDokBIwF2MJO5PZt0SGsGDCgsxtSQFbJMak=,tag:Qn7uvBStCaD+JkL39Re1Kw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:IIJT9oNim6Z1ZA==,iv:CMGp3B7s7KCjias59mTCrZNcFOYgsizIPOvu1K0nAjE=,tag:GSzeC699m8vEpBtsmGQbuA==,type:str]
    namespace: ENC[AES256_GCM,data:z3U2IZn1h7TZcQ==,iv:kRBbqnzMeGfcrdW3RKGUtEGcv+CqPuUmmhKV3DT1nuw=,tag:GmPumQ2aavOC0wJk1GjL2w==,type:str]
type: ENC[AES256_GCM,data:FivZRQxc,iv:PWJWNU2mUIrEEhukXWaztV15R5g+6f0Vq0m8ZZkQiog=,tag:PEHe6SSTdcFxhxsf1dajBg==,type:str]
stringData:
    cloudflare_api_token: ENC[AES256_GCM,data:YRqHEzy0XyTxQrbGI7HzqPU2FtPK8G4kiMcDe4SKwfWKRgxCfOF1PQ==,iv:T5+IDHsWhvpVb35IU1ur1ZTsG4NhL56CdpIzrGAi0N0=,tag:Phd7qOLtkd/bgYMOzHqTmg==,type:str]
sops:
    age:
        - recipient: age1fd94a6m070jjg8y6ke5pghnl7c4vxw7jrvfyqsdgzp2cshel35xseu7365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVVBjWTNrblhESFF2NFZK
            NTFNVDZSK0JKZVJ2QnpudmVYRWcvQlpORkFZClhHbUo3REJGWXZmbHhDeWhuVWph
            VWpWVTA3L1lWVDk2bCsybWlVTU1NZDgKLS0tIG9tbW01SXZxSDgvdnMyM0Y5SHF4
            NTk5SGdaaGpPcHpaSWxyMmlQb1MzUUUKii8zqzy9pGC5tpgDa3eaXKYBGI0Z/fQ7
            fzz/vUC0Ju5zidnmDf5jBWuzzf0l5yoRG/1tHtkxdN3fWh18LRKqOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T01:11:36Z"
    mac: ENC[AES256_GCM,data:RuKpmKDD7P+bHWyyEUtNOHZh2rYC1aQZbUQZRwJodg4klTcz5vJFT3xuH3AqpHHhHIHHa8zJaSJ8aqHFgZTHHlC9uy1U7STUefgCdY6x/O6tdYqc3StpNQYzml639b4V7hwJLNDz0MHBBIZ6kGIzl0QAapyIMyLEWhKO09y9So4=,iv:6IDldP9a2ig/PkSPtUYmBWby71vMejTSTwKx+BxLO5I=,tag:aTLj4pEQROYz+jFaThODuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
