apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: tailscale
type: Opaque
stringData:
    client_id: ENC[AES256_GCM,data:foigJycmqs+k6KByq2p0dZ4=,iv:5BTZy/JaoM8t9krP6UN6ljH18ok5pbE5piqN53bcW4s=,tag:XDU8JCFZtK+uVm0wVDKfGg==,type:str]
    client_secret: ENC[AES256_GCM,data:eYPBeYet9K4+r5sAbVNqvIOjIFmkrFx7LWdP9sKfpF3vmfqiVMH5uPBeyKcM4NR7sVyxwl0RtQ6bHtNqL4af,iv:SjavIdyKxc+mUlmn4cLWSYlWYwf0GmirMTF4VEF483U=,tag:0udF8VHQTbcUb8WZgVVA3g==,type:str]
sops:
    age:
        - recipient: age1fd94a6m070jjg8y6ke5pghnl7c4vxw7jrvfyqsdgzp2cshel35xseu7365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqSzR3ZTA2WmdVSEtpL2FQ
            RlZaU2kzZC9EZHRXTmNlNm10Q1p6TkVGdFhnCjJCRkYzSi92eHpQRzFLdG1pL3dH
            UHNLSUdQTXNmWlpycHowazdNVUNrR3cKLS0tIDBOeEtZOWxLNG1RbTluUHFJSmFx
            VDZ3aE5TenBaclBpZEwyaTBhL0hmU28KoEO/79VyLPu6rM7z0jScFbwOEL2VylP1
            QIZaNPOl7aaHwJU+dGoK1U8l6HttX6YJjQ92A0yuUT3y8iyIzjhLnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-31T16:32:26Z"
    mac: ENC[AES256_GCM,data:HAr9pKtVrrr1DQxwWVjN7e9fuGOz7Sfk8qcZL8gnyK6fWV6Zznc/ObxQkaDZS/npGHBXB8aDNRfInrRhcgBNMnkTJM2iYn2uNVsQVPAOty7B8ZlKQhbw8b5zgj5fv7wj2MqFTbmGz/Au0pnJQqbjrzUwBYR25MUJTOvVk+lc4mY=,iv:KPAImm5kI5YZel9+V00n4yuJa6iaOQAWjfF719DlH1U=,tag:lkCulEjaY+4LR7yJgaWX3w==,type:str]
    encrypted_regex: ^(client_id|client_secret)$
    version: 3.10.2
