apiVersion: v1
kind: PersistentVolume
metadata:
  name: references
  labels:
    type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/srv/persistent/references/"
