apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyparty
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyparty
  template:
    metadata:
      labels:
        app: copyparty
    spec:
      containers:
      - name: copyparty
        image: copyparty/dj:1.19.7
        ports:
        - containerPort: 3923
        volumeMounts:
          - name: config
            mountPath: /cfg
          - name: data
            mountPath: /w
          - name: music-to-import
            mountPath: /w/skarjala/music-to-import
          - name: music
            mountPath: /w/skarjala/music
      volumes:
        - name: config
          configMap:
            name: copyparty-config
            items:
              - key: copyparty.conf
                path: copyparty.conf
        - name: data
          hostPath:
            path: /srv/data/copyparty/
            type: DirectoryOrCreate
        - name: music-to-import
          persistentVolumeClaim:
            claimName: music-to-import
        - name: music
          persistentVolumeClaim:
            claimName: music
---
apiVersion: v1
kind: Service
metadata:
  name: copyparty
  namespace: apps
spec:
  selector:
    app: copyparty
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3923
