apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: references
  namespace: apps
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: references
