apiVersion: ENC[AES256_GCM,data:Whw=,iv:SgNdL1DrLlOenaNAHhw+0lXfPmmy+Vb+Ihpr60huOrc=,tag:9jYoeBSv+jNh3Pb72Gffeg==,type:str]
kind: ENC[AES256_GCM,data:QHkhSfnz,iv:d+SdSTAuGpQAVea0JXswGQrLmZWYRfC0BvdTiXIJQnQ=,tag:r8zf1zS9ovBypXR2KiE0NA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:m/lwO++HNCpiSIZ20FyM,iv:sj7Myh8fyBN84d08NJHC3J7SyKZBIughpe0P/82CDko=,tag:jzGipBjqbGHZq6TnpHD3Ew==,type:str]
    namespace: ENC[AES256_GCM,data:X3csaw==,iv:1SQlWFvpCXUmqsyvlkv6qS5qoZOE3+O7wo3lodrWzrI=,tag:3LnfqrpA+CU/Kws4+FoIZg==,type:str]
type: ENC[AES256_GCM,data:wrMsgnqm,iv:fnWZ+Fcqg9yCHBTUb99WuWluzXDOa/V1AVc9OAtv14s=,tag:bE66SaYhG51Hg/8maoyhJg==,type:str]
stringData:
    http_auth_password: ENC[AES256_GCM,data:wl2VgWtNR6UfiYc3Bev8AiLeufmI3OQ2k0niew8htMA=,iv:oAwZWf9S9F0gytAlwpiYWeTV78ObejmYWwQk71Bk/nM=,tag:653xHvG/QIAcyps5GWU3wg==,type:str]
sops:
    age:
        - recipient: age1fd94a6m070jjg8y6ke5pghnl7c4vxw7jrvfyqsdgzp2cshel35xseu7365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdWcrc0NlTGVldmpJZjU2
            UTViOWRkdXlMQjBHUEZRWGxPTDZMUENqQjJBClVYWU4rVFlhUkcwenFMNTZRWVhz
            MTF4U0w1ZG1QVmVVdmR5MXhiZ3daMFEKLS0tIDNzajB4cXFxVVZRWXpNcno2VW5j
            ZWx6akhLcEJKdmxRS1hvRG01ejNkOGcKafZhfeatwe89yxHdrLBzL24WRdOP9bEc
            azARw4U/4pzaMy9tKA03ypreDITy18gjUZEAAvOmSSQSqb2B40NMMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-24T01:27:36Z"
    mac: ENC[AES256_GCM,data:kl/y72ikiUaSrjnBKg8gYVp7+fCQXBPVEq+C3agAhSY20kVXhPg8iCrBM7rMxKbdbHRVg2h6JtQCUKPJJALoLHo8gxTd/Uf6L9bvIrFL1v1RmtCTW1hT2MNKAonaD94vwFXyUCN/gWw+Otu2fmr9IM54by6wr0gpNDfIQUrAZdc=,iv:/mbkrwljvk3rZwvVpBCmiNpPsW94OMc+Qw+d2VJ0UIQ=,tag:PG+WzjIU79AF/iLNZvqHjQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
