apiVersion: ENC[AES256_GCM,data:RsM=,iv:gKn4dxwOv7Qp+uUo7B6y10rJ8HUAfrj9lCikNUKnIM8=,tag:gZftpdWeL3eJiOJoUo663A==,type:str]
kind: ENC[AES256_GCM,data:7K2Km179,iv:0z2axpiOLqCdtHcZ3fYjSw+FL78HFbwO1nLYvtFlVik=,tag:xnLIT+47wIjFjF9FGwfldg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uQYpvBrnOJFl,iv:FlAoHGCmjzKraVtBdwhpb3RJO2ETLouQ29C1AiUf1og=,tag:vat9pkCQgSx+bn9H5T9EVw==,type:str]
    namespace: ENC[AES256_GCM,data:OYmacg==,iv:yoMuwgdYrIg5/vzMya02hv+nD+z7+tA+su2D3F2NQ1Q=,tag:ewCA3NYGIbNkMAPh3HPlng==,type:str]
type: ENC[AES256_GCM,data:wAGw/ajC,iv:mYqfYNAGdIvCJT1cJHxjZ7emmBLe5WB6n9b/1H2/cl8=,tag:w2UK/Z8pOTGwMOgsiLLGFw==,type:str]
stringData:
    lastfm_api_key: ENC[AES256_GCM,data:3bCA66xIvcCDn3CcET9pQemc88oIhH10MXM/VupyjAM=,iv:hsK/G9F+Dj2HzOdb6H26N8jxB2GBDfn8yp1PKR6AHdo=,tag:tieL41YjOuW5lcprw7E/Rg==,type:str]
    lastfm_secret: ENC[AES256_GCM,data:Bv0kh4cxeK9KgkY0INC7AxuqAfM4xAB7Kd2rLruUzj8=,iv:28Km6cHR7PhqwJGF9HH87BDjEAL3NmFCfwxIHoSYHSI=,tag:IVDVZUCJ5ftakfx55T5WTA==,type:str]
sops:
    age:
        - recipient: age1fd94a6m070jjg8y6ke5pghnl7c4vxw7jrvfyqsdgzp2cshel35xseu7365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RG9hTjRoaWViRjArSlBR
            aXBKS2NEeVdQZ0NqTVJ5bkVrT1Iwc2dTVzBVCitQTXgzenh2MC96dFgvT1I2bExL
            cVV5VWxBQkh1YzhCM0lBTmJWRFE4d0kKLS0tIG05K1NzQnB2cmRhK3JFUmJwb2ll
            SnU0M0tUOFNkb1hvNmVlamFFcWxTWGcKu9ipSt21fOqmGts9E4JTivuFzdKH6TAI
            cAScuztqOQxsisvCe+5a3PEE6FKVSuSVNqSfM7k4L04sPqC+gQz04g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T03:42:10Z"
    mac: ENC[AES256_GCM,data:uU7dWvIr5zG0lgc3lC1vt3rJN4GaG1XTejx6FxEXkWUx+MaKZB8xbzI+JGeo6iSjoSDCLbpjUuNP17RoJ1N1wL48rhj2ySCZ73O8H2tdI7tB78xuPsneyE5iCZssldYuK42E+VxlrNtXrcR7x6n95Pmzto9YsZWvKMzspydlycc=,iv:VmznMdqtnBc+miOYpmg3k9j0OFJ1Tl6rHupSc0QVtKQ=,tag:biTH9RjGivn27KH3mZx5ZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
