apiVersion: ENC[AES256_GCM,data:RpQ=,iv:SyD2qZ2f7OgU2eQiFx5f/vmFFfRfD9wONYJKVShqmUw=,tag:SKwHfCnFRxxuaN2cYm6Yuw==,type:str]
kind: ENC[AES256_GCM,data:sJGuAk0p,iv:HBsNCCkJS5X1DRnh1XS5f37kw/x6pG06l6V/Bs8Ds4Y=,tag:GEHUAuKHkSICyJrkJlYH+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uJk3HDK9OqyV,iv:o0cRCO/Mybzdf6gWoYDKqMyI20TV+aN3n/KbD2P8xP4=,tag:vqPLw1tFZB3kHg0MSts3Ng==,type:str]
    namespace: ENC[AES256_GCM,data:Xvxd0w==,iv:GQdp8Ot2zm4gBTfvok+4GFfELOYOEz3GiKJiny7A0Dc=,tag:z+lI8o8SRs29b8O1RA1qlA==,type:str]
type: ENC[AES256_GCM,data:a0cnXbc9,iv:CGpySYNqxBHs6YNn1O/imaopYp9h+7s9QfSq2LmpNqA=,tag:kUc1guuoJvVbjOB1U0L+SQ==,type:str]
stringData:
    lastfm_api_key: ENC[AES256_GCM,data:HQ9t1OLqRMTQ2ZuiLYHe7ZwwzSq5OHUEQoprzRxMXNg=,iv:hjJ3q7oDLyMs7L3rd0fToZDF8cbQlywZezkX3zdSEpE=,tag:ZpAy7H/rB0erfJuu+RtAng==,type:str]
    lastfm_secret: ENC[AES256_GCM,data:xu3UnEHW/ZYLqBGRD5oDq8WRWWlXoVepO3q2tPtkaYM=,iv:vSeAnKZqc3NqXohpWEY2qedKfw8Mu1RyORDii/m/Bk4=,tag:f9gIzEywj4uCl5Qa2Us3Lw==,type:str]
sops:
    age:
        - recipient: age1fd94a6m070jjg8y6ke5pghnl7c4vxw7jrvfyqsdgzp2cshel35xseu7365
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWmVFOGhWRTM1ejBBZU1L
            Mjk5eHNzancvNDViazNmTFRWSDBIcGkza1EwClVtdGVjWXljQThHS0hjMVgrOUdU
            WTREZnJRVzlGa0tTSkp1U21YeXU5ZnMKLS0tIG1OQmd5Um82b1V2VnZyZXV6V3R6
            OVZGYlhTVUIxWVlFZnphck5rS2RyVDgKXX871Aeq8GfYac9JSXTPbjcEsL/YCbT5
            D5D6vFep2oVs7FFriHrBQJvQHwyqUsJX9g/sHf6tXQV1HOnUyw/Xrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-25T03:46:46Z"
    mac: ENC[AES256_GCM,data:MFVnxItvJMtc5xlFoifc1BqRZ5OqDeMQ0noSE3ROWACmJE+uTuW7KzZD+8t7sHqMTeK2Uj5JZOjSDpD04TBkd5hPOynZg7sslD1+giUdmFTot/eM55GT5U5RwfvFv/JZsCIXLWOpuzctfTfwQFYNd+z2X5fEMxN+2W/7eNZ84QI=,iv:UrD4YSsgRF5tzf1s/ZNlaHJV742RHxgw2oOKlnDabYA=,tag:NId/kFjJyjcDZC0NC4k0ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
